#!/bin/bash
# Lists all of the links between documents
IFS="
"
for FILE in $(find site -name *.txt); do
  for LINE in $(grep -E '^=> (([^ ]+)\.\*|[^. ]+) ' $FILE | grep -Ev '^=> [^ /]+:'); do
    DEST=$(cut "-d " -f2 <<< $LINE)
    if [[ ${DEST: -2} == .* ]]; then
      DEST=${DEST%%.*}.txt
    else
      DEST=${DEST}/index.txt
    fi
    if [[ ${DEST:0:1} == '/' ]]; then
      DEST=site${DEST}
    else
      DEST=$(dirname $FILE)/${DEST}
    fi
    echo $FILE ${DEST} $(cut "-d " -f3- <<< $LINE)
  done
done