#!/bin/bash

if [[ $1 == 'assets' ]]; then
  HTML_PATHS="html/media html/*.woff";
  GMI_PATHS="gmi/media";
else
  HTML_PATHS="html/blog/ html/wiki/ html/*.html html/style.css"
  GMI_PATHS="gmi/gemlog/ gmi/wiki/ gmi/*.gmi"
fi

sh ./build && \
scp -r $HTML_PATHS \
  web@clarity.flowers:/srv/www/clarity.flowers/ &&\
scp -r $GMI_PATHS \
  web@clarity.flowers:/srv/gemini/clarity.flowers/